providers:
  kubernetesCRD:
    enabled: false

  kubernetesIngress:
    enabled: true
    ingressClass: okteto-traefik

rbac:
  enabled: false

serviceAccount:
  name: "default"

service:
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
